import { Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { useState } from 'react';
import { PHASES, initialState, recordClear } from '@well-worth-it/game-core';

export default function Home() {
  const [state, setState] = useState(() => initialState());
  const [gate, setGate] = useState(0);
  const phase = PHASES[state.phaseIndex];
  if (gate < 2) return <SafeAreaView style={styles.gate}><Text style={styles.kicker}>GLOBAL CAREER ACCELERATOR</Text><Text style={styles.title}>{gate === 0 ? 'A student assignment demo.' : 'Demo safety check.'}</Text><Text style={styles.copy}>{gate === 0 ? 'Well Worth It is a concept prototype, not an official charity: water product, fundraising page, or endorsement.' : 'No donations or payment information are collected. Stories, metrics, locations, and leaderboard accounts are synthetic.'}</Text><Pressable accessibilityRole="button" style={styles.button} onPress={() => setGate(gate + 1)}><Text style={styles.buttonText}>{gate === 0 ? 'I understand' : 'Enter demo'}</Text></Pressable></SafeAreaView>;
  return <SafeAreaView style={styles.screen}><Text style={styles.kicker}>DEMO MODE · PHASE {state.phaseIndex + 1} OF 5</Text><Text style={styles.title}>{phase.label}</Text><Text style={styles.copy}>{phase.mechanic}</Text><View style={styles.water}><Text style={styles.waterText}>◎</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Hold to clear sediment" style={styles.button} onPress={() => { const result = recordClear(state, { phaseId: phase.id, durationMs: 1000 }); if (result.accepted) setState(result.state); }}><Text style={styles.buttonText}>Clear sediment · +{phase.reward}</Text></Pressable><Text style={styles.droplets}>{state.droplets.toLocaleString()} droplets</Text><Text style={styles.note}>Offline-ready synthetic demo. No payment flow.</Text></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, padding: 24, backgroundColor: '#FDFBF6', justifyContent: 'center' }, gate: { flex: 1, padding: 24, backgroundColor: '#1A1A1A', justifyContent: 'center' }, kicker: { color: '#0077CC', fontWeight: '800', letterSpacing: 1.5, marginBottom: 12 }, title: { color: '#1A1A1A', fontSize: 40, fontWeight: '900', letterSpacing: -1.5, marginBottom: 16 }, gate: { flex: 1, padding: 24, backgroundColor: '#FDFBF6', justifyContent: 'center' }, copy: { color: '#4d5964', fontSize: 17, lineHeight: 26, marginBottom: 28 }, button: { backgroundColor: '#0077CC', borderRadius: 18, padding: 18, alignItems: 'center' }, buttonText: { color: '#fff', fontWeight: '800', fontSize: 16 }, water: { backgroundColor: '#FFC107', height: 220, borderRadius: 32, justifyContent: 'center', alignItems: 'center', marginBottom: 24 }, waterText: { fontSize: 90, color: '#0077CC' }, droplets: { color: '#1A1A1A', fontWeight: '900', fontSize: 24, textAlign: 'center', marginTop: 24 }, note: { color: '#667085', textAlign: 'center', marginTop: 8 } });
