create type public.demo_status as enum ('synthetic', 'pending-review', 'approved');
create table public.campuses (id uuid primary key default gen_random_uuid(), name text not null, demo_only boolean not null default true);
create table public.teams (id uuid primary key default gen_random_uuid(), campus_id uuid not null references public.campuses(id), name text not null);
create table public.profiles (id uuid primary key references auth.users(id), campus_id uuid references public.campuses(id), team_id uuid references public.teams(id), handle text not null);
create table public.game_sessions (id uuid primary key default gen_random_uuid(), profile_id uuid references public.profiles(id), mode text not null default 'demo', started_at timestamptz not null default now());
create table public.score_events (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.game_sessions(id), phase_id text not null, duration_ms integer not null check (duration_ms between 500 and 30000), reward integer not null check (reward >= 0), created_at timestamptz not null default now(), unique(session_id, phase_id));
create table public.leaderboard_seasons (id uuid primary key default gen_random_uuid(), name text not null, starts_at timestamptz not null, ends_at timestamptz not null);
create table public.content_items (id uuid primary key default gen_random_uuid(), title text not null, quote text not null, attribution text not null, location text not null, story_date date not null, status public.demo_status not null default 'synthetic', source_url text not null);
create table public.content_assets (id uuid primary key default gen_random_uuid(), content_id uuid not null references public.content_items(id), asset_url text not null, license_record text not null);
create table public.partner_links (id uuid primary key default gen_random_uuid(), label text not null, url text not null, status public.demo_status not null default 'pending-review');
alter table public.campuses enable row level security;
alter table public.teams enable row level security;
alter table public.profiles enable row level security;
alter table public.game_sessions enable row level security;
alter table public.score_events enable row level security;
alter table public.leaderboard_seasons enable row level security;
alter table public.content_items enable row level security;
alter table public.content_assets enable row level security;
alter table public.partner_links enable row level security;
create policy "demo content is readable" on public.content_items for select using (status = 'synthetic' or auth.role() = 'authenticated');
create policy "players read own sessions" on public.game_sessions for select using (profile_id = auth.uid());
create policy "players read own events" on public.score_events for select using (session_id in (select id from public.game_sessions where profile_id = auth.uid()));
